//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace ITS.Exwold.Desktop.Reports {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsAuditPalletBatch")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsAuditPalletBatch : global::System.Data.DataSet {
        
        private dtAuditPalletBatchDataTable tabledtAuditPalletBatch;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public dsAuditPalletBatch() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected dsAuditPalletBatch(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dtAuditPalletBatch"] != null)) {
                    base.Tables.Add(new dtAuditPalletBatchDataTable(ds.Tables["dtAuditPalletBatch"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dtAuditPalletBatchDataTable dtAuditPalletBatch {
            get {
                return this.tabledtAuditPalletBatch;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsAuditPalletBatch cln = ((dsAuditPalletBatch)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dtAuditPalletBatch"] != null)) {
                    base.Tables.Add(new dtAuditPalletBatchDataTable(ds.Tables["dtAuditPalletBatch"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabledtAuditPalletBatch = ((dtAuditPalletBatchDataTable)(base.Tables["dtAuditPalletBatch"]));
            if ((initTable == true)) {
                if ((this.tabledtAuditPalletBatch != null)) {
                    this.tabledtAuditPalletBatch.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsAuditPalletBatch";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsAuditPalletBatch.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledtAuditPalletBatch = new dtAuditPalletBatchDataTable();
            base.Tables.Add(this.tabledtAuditPalletBatch);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private bool ShouldSerializedtAuditPalletBatch() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsAuditPalletBatch ds = new dsAuditPalletBatch();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public delegate void dtAuditPalletBatchRowChangeEventHandler(object sender, dtAuditPalletBatchRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dtAuditPalletBatchDataTable : global::System.Data.TypedTableBase<dtAuditPalletBatchRow> {
            
            private global::System.Data.DataColumn columnPalletBatchUniqueNo;
            
            private global::System.Data.DataColumn columnPalletBatchNo;
            
            private global::System.Data.DataColumn columnProductionLineNo;
            
            private global::System.Data.DataColumn columnProductUniqueNo;
            
            private global::System.Data.DataColumn columnProductCode;
            
            private global::System.Data.DataColumn columnProductName;
            
            private global::System.Data.DataColumn columnCustomer;
            
            private global::System.Data.DataColumn columnCustomerDetails;
            
            private global::System.Data.DataColumn columnGMID;
            
            private global::System.Data.DataColumn columnTotalNoOfCartons;
            
            private global::System.Data.DataColumn columnCartonsPerPallet;
            
            private global::System.Data.DataColumn columnInnerPacksPerCarton;
            
            private global::System.Data.DataColumn columnInnerPackWeightOrVolume;
            
            private global::System.Data.DataColumn columnUnitsOfMeasure;
            
            private global::System.Data.DataColumn columnGTIN;
            
            private global::System.Data.DataColumn columnSsccCompanyCode;
            
            private global::System.Data.DataColumn columnSsccProductionLineCustomerCode;
            
            private global::System.Data.DataColumn columnAdditionalInfo;
            
            private global::System.Data.DataColumn columnStartDT;
            
            private global::System.Data.DataColumn columnEndDT;
            
            private global::System.Data.DataColumn columnStatus;
            
            private global::System.Data.DataColumn columnChangeUser;
            
            private global::System.Data.DataColumn columnChangeAction;
            
            private global::System.Data.DataColumn columnChangeDTUTC;
            
            private global::System.Data.DataColumn columnChangeDTLocal;
            
            private global::System.Data.DataColumn columnChangeSqlUser;
            
            private global::System.Data.DataColumn columnChangeUID;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public dtAuditPalletBatchDataTable() {
                this.TableName = "dtAuditPalletBatch";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal dtAuditPalletBatchDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected dtAuditPalletBatchDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn PalletBatchUniqueNoColumn {
                get {
                    return this.columnPalletBatchUniqueNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn PalletBatchNoColumn {
                get {
                    return this.columnPalletBatchNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn ProductionLineNoColumn {
                get {
                    return this.columnProductionLineNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn ProductUniqueNoColumn {
                get {
                    return this.columnProductUniqueNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn ProductCodeColumn {
                get {
                    return this.columnProductCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn ProductNameColumn {
                get {
                    return this.columnProductName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn CustomerColumn {
                get {
                    return this.columnCustomer;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn CustomerDetailsColumn {
                get {
                    return this.columnCustomerDetails;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn GMIDColumn {
                get {
                    return this.columnGMID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn TotalNoOfCartonsColumn {
                get {
                    return this.columnTotalNoOfCartons;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn CartonsPerPalletColumn {
                get {
                    return this.columnCartonsPerPallet;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn InnerPacksPerCartonColumn {
                get {
                    return this.columnInnerPacksPerCarton;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn InnerPackWeightOrVolumeColumn {
                get {
                    return this.columnInnerPackWeightOrVolume;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn UnitsOfMeasureColumn {
                get {
                    return this.columnUnitsOfMeasure;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn GTINColumn {
                get {
                    return this.columnGTIN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn SsccCompanyCodeColumn {
                get {
                    return this.columnSsccCompanyCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn SsccProductionLineCustomerCodeColumn {
                get {
                    return this.columnSsccProductionLineCustomerCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn AdditionalInfoColumn {
                get {
                    return this.columnAdditionalInfo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn StartDTColumn {
                get {
                    return this.columnStartDT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn EndDTColumn {
                get {
                    return this.columnEndDT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn StatusColumn {
                get {
                    return this.columnStatus;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn ChangeUserColumn {
                get {
                    return this.columnChangeUser;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn ChangeActionColumn {
                get {
                    return this.columnChangeAction;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn ChangeDTUTCColumn {
                get {
                    return this.columnChangeDTUTC;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn ChangeDTLocalColumn {
                get {
                    return this.columnChangeDTLocal;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn ChangeSqlUserColumn {
                get {
                    return this.columnChangeSqlUser;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn ChangeUIDColumn {
                get {
                    return this.columnChangeUID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public dtAuditPalletBatchRow this[int index] {
                get {
                    return ((dtAuditPalletBatchRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event dtAuditPalletBatchRowChangeEventHandler dtAuditPalletBatchRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event dtAuditPalletBatchRowChangeEventHandler dtAuditPalletBatchRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event dtAuditPalletBatchRowChangeEventHandler dtAuditPalletBatchRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event dtAuditPalletBatchRowChangeEventHandler dtAuditPalletBatchRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void AdddtAuditPalletBatchRow(dtAuditPalletBatchRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public dtAuditPalletBatchRow AdddtAuditPalletBatchRow(
                        long PalletBatchUniqueNo, 
                        string PalletBatchNo, 
                        int ProductionLineNo, 
                        long ProductUniqueNo, 
                        string ProductCode, 
                        string ProductName, 
                        string Customer, 
                        string CustomerDetails, 
                        string GMID, 
                        int TotalNoOfCartons, 
                        int CartonsPerPallet, 
                        int InnerPacksPerCarton, 
                        double InnerPackWeightOrVolume, 
                        string UnitsOfMeasure, 
                        string GTIN, 
                        string SsccCompanyCode, 
                        string SsccProductionLineCustomerCode, 
                        string AdditionalInfo, 
                        System.DateTime StartDT, 
                        System.DateTime EndDT, 
                        short Status, 
                        string ChangeUser, 
                        string ChangeAction, 
                        System.DateTime ChangeDTUTC, 
                        System.DateTime ChangeDTLocal, 
                        string ChangeSqlUser, 
                        System.Guid ChangeUID) {
                dtAuditPalletBatchRow rowdtAuditPalletBatchRow = ((dtAuditPalletBatchRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        PalletBatchUniqueNo,
                        PalletBatchNo,
                        ProductionLineNo,
                        ProductUniqueNo,
                        ProductCode,
                        ProductName,
                        Customer,
                        CustomerDetails,
                        GMID,
                        TotalNoOfCartons,
                        CartonsPerPallet,
                        InnerPacksPerCarton,
                        InnerPackWeightOrVolume,
                        UnitsOfMeasure,
                        GTIN,
                        SsccCompanyCode,
                        SsccProductionLineCustomerCode,
                        AdditionalInfo,
                        StartDT,
                        EndDT,
                        Status,
                        ChangeUser,
                        ChangeAction,
                        ChangeDTUTC,
                        ChangeDTLocal,
                        ChangeSqlUser,
                        ChangeUID};
                rowdtAuditPalletBatchRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdtAuditPalletBatchRow);
                return rowdtAuditPalletBatchRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dtAuditPalletBatchDataTable cln = ((dtAuditPalletBatchDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dtAuditPalletBatchDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal void InitVars() {
                this.columnPalletBatchUniqueNo = base.Columns["PalletBatchUniqueNo"];
                this.columnPalletBatchNo = base.Columns["PalletBatchNo"];
                this.columnProductionLineNo = base.Columns["ProductionLineNo"];
                this.columnProductUniqueNo = base.Columns["ProductUniqueNo"];
                this.columnProductCode = base.Columns["ProductCode"];
                this.columnProductName = base.Columns["ProductName"];
                this.columnCustomer = base.Columns["Customer"];
                this.columnCustomerDetails = base.Columns["CustomerDetails"];
                this.columnGMID = base.Columns["GMID"];
                this.columnTotalNoOfCartons = base.Columns["TotalNoOfCartons"];
                this.columnCartonsPerPallet = base.Columns["CartonsPerPallet"];
                this.columnInnerPacksPerCarton = base.Columns["InnerPacksPerCarton"];
                this.columnInnerPackWeightOrVolume = base.Columns["InnerPackWeightOrVolume"];
                this.columnUnitsOfMeasure = base.Columns["UnitsOfMeasure"];
                this.columnGTIN = base.Columns["GTIN"];
                this.columnSsccCompanyCode = base.Columns["SsccCompanyCode"];
                this.columnSsccProductionLineCustomerCode = base.Columns["SsccProductionLineCustomerCode"];
                this.columnAdditionalInfo = base.Columns["AdditionalInfo"];
                this.columnStartDT = base.Columns["StartDT"];
                this.columnEndDT = base.Columns["EndDT"];
                this.columnStatus = base.Columns["Status"];
                this.columnChangeUser = base.Columns["ChangeUser"];
                this.columnChangeAction = base.Columns["ChangeAction"];
                this.columnChangeDTUTC = base.Columns["ChangeDTUTC"];
                this.columnChangeDTLocal = base.Columns["ChangeDTLocal"];
                this.columnChangeSqlUser = base.Columns["ChangeSqlUser"];
                this.columnChangeUID = base.Columns["ChangeUID"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            private void InitClass() {
                this.columnPalletBatchUniqueNo = new global::System.Data.DataColumn("PalletBatchUniqueNo", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPalletBatchUniqueNo);
                this.columnPalletBatchNo = new global::System.Data.DataColumn("PalletBatchNo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPalletBatchNo);
                this.columnProductionLineNo = new global::System.Data.DataColumn("ProductionLineNo", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnProductionLineNo);
                this.columnProductUniqueNo = new global::System.Data.DataColumn("ProductUniqueNo", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnProductUniqueNo);
                this.columnProductCode = new global::System.Data.DataColumn("ProductCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnProductCode);
                this.columnProductName = new global::System.Data.DataColumn("ProductName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnProductName);
                this.columnCustomer = new global::System.Data.DataColumn("Customer", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCustomer);
                this.columnCustomerDetails = new global::System.Data.DataColumn("CustomerDetails", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCustomerDetails);
                this.columnGMID = new global::System.Data.DataColumn("GMID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGMID);
                this.columnTotalNoOfCartons = new global::System.Data.DataColumn("TotalNoOfCartons", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTotalNoOfCartons);
                this.columnCartonsPerPallet = new global::System.Data.DataColumn("CartonsPerPallet", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCartonsPerPallet);
                this.columnInnerPacksPerCarton = new global::System.Data.DataColumn("InnerPacksPerCarton", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnInnerPacksPerCarton);
                this.columnInnerPackWeightOrVolume = new global::System.Data.DataColumn("InnerPackWeightOrVolume", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnInnerPackWeightOrVolume);
                this.columnUnitsOfMeasure = new global::System.Data.DataColumn("UnitsOfMeasure", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUnitsOfMeasure);
                this.columnGTIN = new global::System.Data.DataColumn("GTIN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGTIN);
                this.columnSsccCompanyCode = new global::System.Data.DataColumn("SsccCompanyCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSsccCompanyCode);
                this.columnSsccProductionLineCustomerCode = new global::System.Data.DataColumn("SsccProductionLineCustomerCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSsccProductionLineCustomerCode);
                this.columnAdditionalInfo = new global::System.Data.DataColumn("AdditionalInfo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAdditionalInfo);
                this.columnStartDT = new global::System.Data.DataColumn("StartDT", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnStartDT);
                this.columnEndDT = new global::System.Data.DataColumn("EndDT", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEndDT);
                this.columnStatus = new global::System.Data.DataColumn("Status", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnStatus);
                this.columnChangeUser = new global::System.Data.DataColumn("ChangeUser", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnChangeUser);
                this.columnChangeAction = new global::System.Data.DataColumn("ChangeAction", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnChangeAction);
                this.columnChangeDTUTC = new global::System.Data.DataColumn("ChangeDTUTC", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnChangeDTUTC);
                this.columnChangeDTLocal = new global::System.Data.DataColumn("ChangeDTLocal", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnChangeDTLocal);
                this.columnChangeSqlUser = new global::System.Data.DataColumn("ChangeSqlUser", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnChangeSqlUser);
                this.columnChangeUID = new global::System.Data.DataColumn("ChangeUID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnChangeUID);
                this.columnPalletBatchUniqueNo.ReadOnly = true;
                this.columnPalletBatchNo.ReadOnly = true;
                this.columnPalletBatchNo.MaxLength = 20;
                this.columnProductionLineNo.ReadOnly = true;
                this.columnProductUniqueNo.ReadOnly = true;
                this.columnProductCode.ReadOnly = true;
                this.columnProductCode.MaxLength = 50;
                this.columnProductName.ReadOnly = true;
                this.columnProductName.MaxLength = 50;
                this.columnCustomer.ReadOnly = true;
                this.columnCustomer.MaxLength = 50;
                this.columnCustomerDetails.ReadOnly = true;
                this.columnCustomerDetails.MaxLength = 50;
                this.columnGMID.ReadOnly = true;
                this.columnGMID.MaxLength = 20;
                this.columnTotalNoOfCartons.ReadOnly = true;
                this.columnCartonsPerPallet.ReadOnly = true;
                this.columnInnerPacksPerCarton.ReadOnly = true;
                this.columnInnerPackWeightOrVolume.ReadOnly = true;
                this.columnUnitsOfMeasure.ReadOnly = true;
                this.columnUnitsOfMeasure.MaxLength = 10;
                this.columnGTIN.ReadOnly = true;
                this.columnGTIN.MaxLength = 14;
                this.columnSsccCompanyCode.ReadOnly = true;
                this.columnSsccCompanyCode.MaxLength = 9;
                this.columnSsccProductionLineCustomerCode.ReadOnly = true;
                this.columnSsccProductionLineCustomerCode.MaxLength = 1;
                this.columnAdditionalInfo.ReadOnly = true;
                this.columnAdditionalInfo.MaxLength = 2147483647;
                this.columnStartDT.ReadOnly = true;
                this.columnEndDT.ReadOnly = true;
                this.columnStatus.ReadOnly = true;
                this.columnChangeUser.ReadOnly = true;
                this.columnChangeUser.MaxLength = 50;
                this.columnChangeAction.ReadOnly = true;
                this.columnChangeAction.MaxLength = 20;
                this.columnChangeDTUTC.ReadOnly = true;
                this.columnChangeDTLocal.ReadOnly = true;
                this.columnChangeSqlUser.ReadOnly = true;
                this.columnChangeSqlUser.MaxLength = 50;
                this.columnChangeUID.ReadOnly = true;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public dtAuditPalletBatchRow NewdtAuditPalletBatchRow() {
                return ((dtAuditPalletBatchRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dtAuditPalletBatchRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dtAuditPalletBatchRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dtAuditPalletBatchRowChanged != null)) {
                    this.dtAuditPalletBatchRowChanged(this, new dtAuditPalletBatchRowChangeEvent(((dtAuditPalletBatchRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dtAuditPalletBatchRowChanging != null)) {
                    this.dtAuditPalletBatchRowChanging(this, new dtAuditPalletBatchRowChangeEvent(((dtAuditPalletBatchRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dtAuditPalletBatchRowDeleted != null)) {
                    this.dtAuditPalletBatchRowDeleted(this, new dtAuditPalletBatchRowChangeEvent(((dtAuditPalletBatchRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dtAuditPalletBatchRowDeleting != null)) {
                    this.dtAuditPalletBatchRowDeleting(this, new dtAuditPalletBatchRowChangeEvent(((dtAuditPalletBatchRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void RemovedtAuditPalletBatchRow(dtAuditPalletBatchRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsAuditPalletBatch ds = new dsAuditPalletBatch();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dtAuditPalletBatchDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dtAuditPalletBatchRow : global::System.Data.DataRow {
            
            private dtAuditPalletBatchDataTable tabledtAuditPalletBatch;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal dtAuditPalletBatchRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledtAuditPalletBatch = ((dtAuditPalletBatchDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public long PalletBatchUniqueNo {
                get {
                    try {
                        return ((long)(this[this.tabledtAuditPalletBatch.PalletBatchUniqueNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PalletBatchUniqueNo\' in table \'dtAuditPalletBatch\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.PalletBatchUniqueNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string PalletBatchNo {
                get {
                    try {
                        return ((string)(this[this.tabledtAuditPalletBatch.PalletBatchNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PalletBatchNo\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.PalletBatchNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int ProductionLineNo {
                get {
                    try {
                        return ((int)(this[this.tabledtAuditPalletBatch.ProductionLineNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ProductionLineNo\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.ProductionLineNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public long ProductUniqueNo {
                get {
                    try {
                        return ((long)(this[this.tabledtAuditPalletBatch.ProductUniqueNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ProductUniqueNo\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.ProductUniqueNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string ProductCode {
                get {
                    try {
                        return ((string)(this[this.tabledtAuditPalletBatch.ProductCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ProductCode\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.ProductCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string ProductName {
                get {
                    try {
                        return ((string)(this[this.tabledtAuditPalletBatch.ProductNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ProductName\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.ProductNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Customer {
                get {
                    try {
                        return ((string)(this[this.tabledtAuditPalletBatch.CustomerColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Customer\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.CustomerColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string CustomerDetails {
                get {
                    try {
                        return ((string)(this[this.tabledtAuditPalletBatch.CustomerDetailsColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CustomerDetails\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.CustomerDetailsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string GMID {
                get {
                    try {
                        return ((string)(this[this.tabledtAuditPalletBatch.GMIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'GMID\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.GMIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int TotalNoOfCartons {
                get {
                    try {
                        return ((int)(this[this.tabledtAuditPalletBatch.TotalNoOfCartonsColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TotalNoOfCartons\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.TotalNoOfCartonsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int CartonsPerPallet {
                get {
                    try {
                        return ((int)(this[this.tabledtAuditPalletBatch.CartonsPerPalletColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CartonsPerPallet\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.CartonsPerPalletColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int InnerPacksPerCarton {
                get {
                    try {
                        return ((int)(this[this.tabledtAuditPalletBatch.InnerPacksPerCartonColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'InnerPacksPerCarton\' in table \'dtAuditPalletBatch\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.InnerPacksPerCartonColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public double InnerPackWeightOrVolume {
                get {
                    try {
                        return ((double)(this[this.tabledtAuditPalletBatch.InnerPackWeightOrVolumeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'InnerPackWeightOrVolume\' in table \'dtAuditPalletBatch\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.InnerPackWeightOrVolumeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string UnitsOfMeasure {
                get {
                    try {
                        return ((string)(this[this.tabledtAuditPalletBatch.UnitsOfMeasureColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'UnitsOfMeasure\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.UnitsOfMeasureColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string GTIN {
                get {
                    try {
                        return ((string)(this[this.tabledtAuditPalletBatch.GTINColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'GTIN\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.GTINColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string SsccCompanyCode {
                get {
                    try {
                        return ((string)(this[this.tabledtAuditPalletBatch.SsccCompanyCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SsccCompanyCode\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.SsccCompanyCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string SsccProductionLineCustomerCode {
                get {
                    try {
                        return ((string)(this[this.tabledtAuditPalletBatch.SsccProductionLineCustomerCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SsccProductionLineCustomerCode\' in table \'dtAuditPalletBatc" +
                                "h\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.SsccProductionLineCustomerCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string AdditionalInfo {
                get {
                    try {
                        return ((string)(this[this.tabledtAuditPalletBatch.AdditionalInfoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AdditionalInfo\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.AdditionalInfoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public System.DateTime StartDT {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledtAuditPalletBatch.StartDTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'StartDT\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.StartDTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public System.DateTime EndDT {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledtAuditPalletBatch.EndDTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EndDT\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.EndDTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public short Status {
                get {
                    try {
                        return ((short)(this[this.tabledtAuditPalletBatch.StatusColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Status\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.StatusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string ChangeUser {
                get {
                    try {
                        return ((string)(this[this.tabledtAuditPalletBatch.ChangeUserColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ChangeUser\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.ChangeUserColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string ChangeAction {
                get {
                    try {
                        return ((string)(this[this.tabledtAuditPalletBatch.ChangeActionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ChangeAction\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.ChangeActionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public System.DateTime ChangeDTUTC {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledtAuditPalletBatch.ChangeDTUTCColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ChangeDTUTC\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.ChangeDTUTCColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public System.DateTime ChangeDTLocal {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledtAuditPalletBatch.ChangeDTLocalColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ChangeDTLocal\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.ChangeDTLocalColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string ChangeSqlUser {
                get {
                    try {
                        return ((string)(this[this.tabledtAuditPalletBatch.ChangeSqlUserColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ChangeSqlUser\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.ChangeSqlUserColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public System.Guid ChangeUID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tabledtAuditPalletBatch.ChangeUIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ChangeUID\' in table \'dtAuditPalletBatch\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtAuditPalletBatch.ChangeUIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsPalletBatchUniqueNoNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.PalletBatchUniqueNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetPalletBatchUniqueNoNull() {
                this[this.tabledtAuditPalletBatch.PalletBatchUniqueNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsPalletBatchNoNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.PalletBatchNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetPalletBatchNoNull() {
                this[this.tabledtAuditPalletBatch.PalletBatchNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsProductionLineNoNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.ProductionLineNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetProductionLineNoNull() {
                this[this.tabledtAuditPalletBatch.ProductionLineNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsProductUniqueNoNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.ProductUniqueNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetProductUniqueNoNull() {
                this[this.tabledtAuditPalletBatch.ProductUniqueNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsProductCodeNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.ProductCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetProductCodeNull() {
                this[this.tabledtAuditPalletBatch.ProductCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsProductNameNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.ProductNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetProductNameNull() {
                this[this.tabledtAuditPalletBatch.ProductNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsCustomerNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.CustomerColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetCustomerNull() {
                this[this.tabledtAuditPalletBatch.CustomerColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsCustomerDetailsNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.CustomerDetailsColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetCustomerDetailsNull() {
                this[this.tabledtAuditPalletBatch.CustomerDetailsColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsGMIDNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.GMIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetGMIDNull() {
                this[this.tabledtAuditPalletBatch.GMIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsTotalNoOfCartonsNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.TotalNoOfCartonsColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetTotalNoOfCartonsNull() {
                this[this.tabledtAuditPalletBatch.TotalNoOfCartonsColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsCartonsPerPalletNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.CartonsPerPalletColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetCartonsPerPalletNull() {
                this[this.tabledtAuditPalletBatch.CartonsPerPalletColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsInnerPacksPerCartonNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.InnerPacksPerCartonColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetInnerPacksPerCartonNull() {
                this[this.tabledtAuditPalletBatch.InnerPacksPerCartonColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsInnerPackWeightOrVolumeNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.InnerPackWeightOrVolumeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetInnerPackWeightOrVolumeNull() {
                this[this.tabledtAuditPalletBatch.InnerPackWeightOrVolumeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsUnitsOfMeasureNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.UnitsOfMeasureColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetUnitsOfMeasureNull() {
                this[this.tabledtAuditPalletBatch.UnitsOfMeasureColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsGTINNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.GTINColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetGTINNull() {
                this[this.tabledtAuditPalletBatch.GTINColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsSsccCompanyCodeNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.SsccCompanyCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetSsccCompanyCodeNull() {
                this[this.tabledtAuditPalletBatch.SsccCompanyCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsSsccProductionLineCustomerCodeNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.SsccProductionLineCustomerCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetSsccProductionLineCustomerCodeNull() {
                this[this.tabledtAuditPalletBatch.SsccProductionLineCustomerCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsAdditionalInfoNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.AdditionalInfoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetAdditionalInfoNull() {
                this[this.tabledtAuditPalletBatch.AdditionalInfoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsStartDTNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.StartDTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetStartDTNull() {
                this[this.tabledtAuditPalletBatch.StartDTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsEndDTNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.EndDTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetEndDTNull() {
                this[this.tabledtAuditPalletBatch.EndDTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsStatusNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.StatusColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetStatusNull() {
                this[this.tabledtAuditPalletBatch.StatusColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsChangeUserNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.ChangeUserColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetChangeUserNull() {
                this[this.tabledtAuditPalletBatch.ChangeUserColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsChangeActionNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.ChangeActionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetChangeActionNull() {
                this[this.tabledtAuditPalletBatch.ChangeActionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsChangeDTUTCNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.ChangeDTUTCColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetChangeDTUTCNull() {
                this[this.tabledtAuditPalletBatch.ChangeDTUTCColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsChangeDTLocalNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.ChangeDTLocalColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetChangeDTLocalNull() {
                this[this.tabledtAuditPalletBatch.ChangeDTLocalColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsChangeSqlUserNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.ChangeSqlUserColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetChangeSqlUserNull() {
                this[this.tabledtAuditPalletBatch.ChangeSqlUserColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsChangeUIDNull() {
                return this.IsNull(this.tabledtAuditPalletBatch.ChangeUIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetChangeUIDNull() {
                this[this.tabledtAuditPalletBatch.ChangeUIDColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public class dtAuditPalletBatchRowChangeEvent : global::System.EventArgs {
            
            private dtAuditPalletBatchRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public dtAuditPalletBatchRowChangeEvent(dtAuditPalletBatchRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public dtAuditPalletBatchRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591